apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- ../common/cert-manager/cert-manager/base
- ../common/cert-manager/kubeflow-issuer/base
# Istio
- ../common/istio-1-11/istio-crds/base
- ../common/istio-1-11/istio-namespace/base
- ../common/istio-1-11/istio-install/base
# OIDC Authservice
- ../common/oidc-authservice/base
# Dex
- ../common/dex/overlays/istio
# KNative
- ../common/knative/knative-serving/overlays/gateways
- ../common/knative/knative-eventing/base
- ../common/istio-1-11/cluster-local-gateway/base
# Kubeflow namespace
- ../common/kubeflow-namespace/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-11/kubeflow-istio-resources/base


# Kubeflow Pipelines
- ../apps/pipeline/upstream/env/platform-agnostic-multi-user
# KFServing
- ../apps/kfserving/upstream/overlays/kubeflow
# Katib
- ../apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../apps/centraldashboard/upstream/overlays/kserve
# Admission Webhook
- ../apps/admission-webhook/upstream/overlays/cert-manager
# Notebook Controller
- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Jupyter Web App
- ../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
-  ../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
-  ../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../apps/training-operator/upstream/overlays/kubeflow
# User namespace
- ../common/user-namespace/base

# KServe
- ../contrib/kserve/kserve
- ../contrib/kserve/models-web-app/overlays/kubeflow

# 替换自己的镜像，因为国外的镜像很难拉
images:
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller
  newName: zhuyaguang/public.ecr.aws.j1r0q0g6.notebooks.tensorboard-controller
  newTag: v1.5.0
- name: gcr.io/ml-pipeline/minio
  newName: zhuyaguang/gcr.io.ml-pipeline.minio
  newTag: RELEASE.2019-08-14T20-37-41Z-license-compliance
- name: gcr.io/ml-pipeline/cache-deployer
  newName: togettoyou/gcr.io.ml-pipeline.cache-deployer
  newTag: 1.8.1
- name: gcr.io/ml-pipeline/cache-server
  newName: zhuyaguang/gcr.io.ml-pipeline.cache-server
  newTag: 1.8.1
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: togettoyou/gcr.io.kubebuilder.kube-rbac-proxy
  newTag: v0.4.0
- name: gcr.io/ml-pipeline/metadata-envoy
  newName: zhuyaguang/gcr.io.ml-pipeline.metadata-envoy
  newTag: 1.8.1
- name: gcr.io/tfx-oss-public/ml_metadata_store_server
  newName: togettoyou/gcr.io.tfx-oss-public.ml_metadata_store_server
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/metadata-writer
  newName: togettoyou/gcr.io.ml-pipeline.metadata-writer
  newTag: 1.8.1
- name: gcr.io/ml-pipeline/api-server
  newName: togettoyou/gcr.io.ml-pipeline.api-server
  newTag: 1.8.1
- name: gcr.io/ml-pipeline/persistenceagent
  newName: togettoyou/gcr.io.ml-pipeline.persistenceagent
  newTag: 1.8.1
- name: gcr.io/ml-pipeline/scheduledworkflow
  newName: togettoyou/gcr.io.ml-pipeline.scheduledworkflow
  newTag: 1.8.1
- name: gcr.io/ml-pipeline/frontend
  newName: togettoyou/gcr.io.ml-pipeline.frontend
  newTag: 1.8.1
- name: gcr.io/ml-pipeline/viewer-crd-controller
  newName: togettoyou/gcr.io.ml-pipeline.viewer-crd-controller
  newTag: 1.8.1
- name: gcr.io/ml-pipeline/visualization-server
  newName: togettoyou/gcr.io.ml-pipeline.visualization-server
  newTag: 1.8.1
- name: gcr.io/ml-pipeline/mysql
  newName: zhuyaguang/gcr.io.ml-pipeline.mysql
  newTag: "5.7"
- name: gcr.io/ml-pipeline/workflow-controller
  newName: togettoyou/gcr.io.ml-pipeline.workflow-controller
  newTag: v3.1.6-patch-license-compliance

- name: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook
  newName: goodpp/admission-webhook
  newTag: v1.4
- name: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard
  newName: goodpp/central-dashboard
  newTag: v1.4
- name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
  newName: goodpp/jupyter-web-app
  newTag: v1.4
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newName: goodpp/access-management
  newTag: v1.4
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newName: goodpp/tensorboards-web-app
  newTag: v1.4
- name: public.ecr.aws/j1r0q0g6/training/training-operator
  newName: goodpp/training-operator
  newTag: 760ac1171dd30039a7363ffa03c77454bd714da5
- name: public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app
  newName: goodpp/volumes-web-app
  newTag: v1.4
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: zhuyaguang/gcr.io.arrikto.kubeflow.oidc-authservice
  newTag: 28c59ef
- name: public.ecr.aws/j1r0q0g6/notebooks/profile-controller
  newName: zhuyaguang/public.ecr.aws.j1r0q0g6.notebooks.profile-controller
  newTag: v1.5.0
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: zhuyaguang/public.ecr.aws.j1r0q0g6.notebooks.notebook-controller
  newTag: v1.5.0