apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          image: togettoyou/gcr.io.ml-pipeline.workflow-controller:v3.2.3-license-compliance
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - zhuyaguang/gcr.io.ml-pipeline.argoexec:v3.2.3-license-compliance
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
